/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Managing;

/**
 *
 * @author Giridhar
 */
public class ProductPerformanceJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProductPerformanceJPanel
     */
    public ProductPerformanceJPanel() {
        initComponents();
        userProcessContainer = upc;
        bb=b;
        supplierDirectory= b.getSupplierDirectory();
        this.cust=cp;
        
        cmbsupplier.removeAllItems();
        for(Supplier supplier : supplierDirectory.getSuplierList()) {
            cmbsupplier.addItem(supplier.getName());
         
        }
        refreshprod();
    }
    public void refreshprod(){
    
    int rc = tblCatalog.getRowCount();
        int i;
        for (i = rc - 1; i >= 0; i--) {
            ((DefaultTableModel) tblCatalog.getModel()).removeRow(i);
        }
        for(Supplier s: supplierDirectory.getSuplierList()){
     for(Product p: s.getProductCatalog().getProductList())  {
     
     
      Object[] row = new Object[4];
            row[0] = p;
            row[1] = p.getFloorPrice();
            row[2] = p.getCeilingPrice();
            
           row[3] = p.getTargetPrice();    
//           row[4]=p.;

            ((DefaultTableModel) tblCatalog.getModel()).addRow(row);
     
     } }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
