/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Managing;

<<<<<<< HEAD
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Business.Business;
import model.CustomerManagement.CustomerProfile;
import model.OrderManagement.MasterOrderList;
import model.OrderManagement.Order;
import model.OrderManagement.OrderItem;
import model.ProductManagement.Product;
import model.Supplier.Supplier;
import model.Supplier.SupplierDirectory;

=======
>>>>>>> 8310a4261655bc488a8677b20f978d8f1c716a01
/**
 *
 * @author Giridhar
 */
public class ProductPerformanceJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProductPerformanceJPanel
     */
<<<<<<< HEAD
    private JPanel userProcessContainer;
    private SupplierDirectory supplierDirectory;
    Business bb;
    CustomerProfile cust;
    Product p1;
    
    public ProductPerformanceJPanel(JPanel upc, Business b,CustomerProfile cp) {
=======
    public ProductPerformanceJPanel() {
>>>>>>> 8310a4261655bc488a8677b20f978d8f1c716a01
        initComponents();
        userProcessContainer = upc;
        bb=b;
        supplierDirectory= b.getSupplierDirectory();
        this.cust=cp;
        
        cmbsupplier.removeAllItems();
        for(Supplier supplier : supplierDirectory.getSuplierList()) {
            cmbsupplier.addItem(supplier.getName());
         
        }
        refreshprod();
    }
    public void refreshprod(){
    
    int rc = tblCatalog.getRowCount();
        int i;
        for (i = rc - 1; i >= 0; i--) {
            ((DefaultTableModel) tblCatalog.getModel()).removeRow(i);
        }
        for(Supplier s: supplierDirectory.getSuplierList()){
     for(Product p: s.getProductCatalog().getProductList())  {
     
     
      Object[] row = new Object[4];
            row[0] = p;
            row[1] = p.getFloorPrice();
            row[2] = p.getCeilingPrice();
            
           row[3] = p.getTargetPrice();    
//           row[4]=p.;

            ((DefaultTableModel) tblCatalog.getModel()).addRow(row);
     
     } }
<<<<<<< HEAD
=======
    
>>>>>>> 8310a4261655bc488a8677b20f978d8f1c716a01
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

<<<<<<< HEAD
        jLabel10 = new javax.swing.JLabel();
        btnBook = new javax.swing.JButton();
        txtActualPrice1 = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCatalog = new javax.swing.JTable();
        txtActualPrice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtProductName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFrequencyAboveTarget = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnRemove = new javax.swing.JButton();
        txtFrequencyBelowTarget = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbsupplier = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Order Quantity");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 260, 125, 30));

        btnBook.setBackground(new java.awt.Color(204, 255, 204));
        btnBook.setText("Book");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });
        add(btnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 540, 125, -1));
        add(txtActualPrice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, 125, 28));

        btnCancel.setText("Cancel All");
        add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 500, 125, -1));

        tblCatalog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Floor Price", "Ceiling Price", "Target Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCatalog);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 195, 723, 181));
        add(txtActualPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 220, 125, 28));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Business-wide Product Intelligence");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 603, 224, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product", "Actual price", "Quantity", "Item total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 416, 715, 181));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Product Name");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 645, 142, 33));
        add(txtProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 684, 140, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Frequency Above Target");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 645, 142, 33));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Order items");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 376, 132, 28));
        add(txtFrequencyAboveTarget, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 684, 140, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Actual Price");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 190, 125, 27));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Frequency Below Target");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 645, 142, 33));

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 470, 125, -1));
        add(txtFrequencyBelowTarget, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 684, 140, -1));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 350, 125, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Catalog");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 149, 62, 28));

        jLabel2.setText("Brand");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 84, 132, 22));

        cmbsupplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbsupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbsupplierActionPerformed(evt);
            }
        });
        add(cmbsupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 84, 166, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sales - Prepare Order");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 17, 1055, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBookActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if(txtActualPrice==null){
            JOptionPane.showMessageDialog(null, "Please Enter Actual Price", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(txtActualPrice1==null){
            JOptionPane.showMessageDialog(null, "Please Enter Actual Price", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int actp= Integer.parseInt(txtActualPrice.getText());
        int quant= Integer.parseInt(txtActualPrice1.getText());

        int row = tblCatalog.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Product s = (Product) tblCatalog.getValueAt(row, 0);

        MasterOrderList mol =  bb.getMasterOrderList();
        Order order1 = mol.newOrder(cust);
        order1.newOrderItem(s,actp,quant);
        //        cust.addCustomerOrder(order1);
        refreshorder();
    }//GEN-LAST:event_btnAddActionPerformed

    public void refreshorder(){

   int rc = jTable2.getRowCount();
        int i;
        for (i = rc - 1; i >= 0; i--) {
            ((DefaultTableModel) jTable2.getModel()).removeRow(i);
        }
//                MasterOrderList mol =  bb.getMasterOrderList();
        ArrayList<Order> s= cust.getOrders();
        System.out.println(s);
         for (Order a: s ){
                     System.out.println(a);

             for(OrderItem l: a.getOrderitems())
             {
                                      System.out.println(l);

                 Object[] row = new Object[4];
            row[0] = l;
            row[1] = l.getActualPrice();
            row[2] = l.getQuantity();
            
           row[3] = l.getOrderItemTotal();    
//           row[4]=p.;

            ((DefaultTableModel) jTable2.getModel()).addRow(row);
   
             }
         }
        

    }
    
    private void cmbsupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbsupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbsupplierActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRemove;
    private javax.swing.JComboBox<String> cmbsupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tblCatalog;
    private javax.swing.JTextField txtActualPrice;
    private javax.swing.JTextField txtActualPrice1;
    private javax.swing.JTextField txtFrequencyAboveTarget;
    private javax.swing.JTextField txtFrequencyBelowTarget;
    private javax.swing.JTextField txtProductName;
=======
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
>>>>>>> 8310a4261655bc488a8677b20f978d8f1c716a01
    // End of variables declaration//GEN-END:variables
}
