/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.workSpaceProfiles;

import model.Business.Business;

/**
 *
 * @author KAILASH
 */
public class MarketingManagerWorkAreaJPanel extends javax.swing.JPanel {

    javax.swing.JPanel CardSequencePanel;
    Business business;
    
    /**
     * Creates new form MarketingManagerWorkAreaJPanel
     */
    public MarketingManagerWorkAreaJPanel(Business business, JPanel jPanel) {
        initComponents();
        business = business;
        this.CardSequencePanel = jPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageMarkets = new javax.swing.JButton();
        btnManageChannels = new javax.swing.JButton();
        btnManagePrices = new javax.swing.JButton();
        btnPerformanceReports = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnManageMarkets.setBackground(new java.awt.Color(102, 153, 255));
        btnManageMarkets.setForeground(new java.awt.Color(255, 255, 255));
        btnManageMarkets.setText("Manage Markets");
        btnManageMarkets.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageMarkets.setMaximumSize(new java.awt.Dimension(200, 40));
        btnManageMarkets.setMinimumSize(new java.awt.Dimension(20, 23));
        btnManageMarkets.setPreferredSize(new java.awt.Dimension(240, 30));
        btnManageMarkets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageMarketsIdentifyResourceAssetsActionPerformed(evt);
            }
        });
        add(btnManageMarkets, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        btnManageChannels.setBackground(new java.awt.Color(102, 153, 255));
        btnManageChannels.setForeground(new java.awt.Color(255, 255, 255));
        btnManageChannels.setText("Manage Channels");
        btnManageChannels.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageChannels.setMaximumSize(new java.awt.Dimension(200, 40));
        btnManageChannels.setMinimumSize(new java.awt.Dimension(20, 20));
        btnManageChannels.setPreferredSize(new java.awt.Dimension(240, 25));
        btnManageChannels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageChannelsActionPerformed(evt);
            }
        });
        add(btnManageChannels, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 195, -1, 30));

        btnManagePrices.setBackground(new java.awt.Color(102, 153, 255));
        btnManagePrices.setForeground(new java.awt.Color(255, 255, 255));
        btnManagePrices.setText("Manage Prices");
        btnManagePrices.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManagePrices.setMaximumSize(new java.awt.Dimension(145, 40));
        btnManagePrices.setMinimumSize(new java.awt.Dimension(20, 20));
        btnManagePrices.setPreferredSize(new java.awt.Dimension(240, 25));
        btnManagePrices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePricesIdentifyEventsActionPerformed(evt);
            }
        });
        add(btnManagePrices, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        btnPerformanceReports.setBackground(new java.awt.Color(102, 153, 255));
        btnPerformanceReports.setForeground(new java.awt.Color(255, 255, 255));
        btnPerformanceReports.setText("Performance Reports");
        btnPerformanceReports.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPerformanceReports.setMaximumSize(new java.awt.Dimension(200, 40));
        btnPerformanceReports.setMinimumSize(new java.awt.Dimension(20, 20));
        btnPerformanceReports.setPreferredSize(new java.awt.Dimension(240, 25));
        btnPerformanceReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerformanceReportsActionPerformed(evt);
            }
        });
        add(btnPerformanceReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 195, -1, 30));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Marketing ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageMarketsIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageMarketsIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.removeAll();

        ManageTheBusinessJPanel aos = new ManageTheBusinessJPanel(business, CardSequencePanel);

        CardSequencePanel.add("ManageVulns", aos);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnManageMarketsIdentifyResourceAssetsActionPerformed

    private void btnManageChannelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageChannelsActionPerformed
        // TODO add your handling code here:

        ManageSuppliersJPanel iet = new ManageSuppliersJPanel(business, CardSequencePanel);

        CardSequencePanel.add("FindResourceAsset", iet);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnManageChannelsActionPerformed

    private void btnManagePricesIdentifyEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePricesIdentifyEventsActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.removeAll();
        //    IdentifyEventTypes iet= new IdentifyEventTypes(businessunit, CardSequencePanel);

        //    CardSequencePanel.add("IdentifyEventTypes", iet);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
        //((java.awt.CardLayout)CardSequencePanel.getLayout()).show(CardSequencePanel, "IdentifyEventTypes");
    }//GEN-LAST:event_btnManagePricesIdentifyEventsActionPerformed

    private void btnPerformanceReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerformanceReportsActionPerformed
        // TODO add your handling code here:

        CardSequencePanel.removeAll();
        //        ManageIncidents aos = new  ManageIncidents(businessunit, CardSequencePanel);
        // aos.setAgenda(businessunit.getRiskManagementAgenda());
        //        CardSequencePanel.add("RiskAgendaObjectives", aos);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnPerformanceReportsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageChannels;
    private javax.swing.JButton btnManageMarkets;
    private javax.swing.JButton btnManagePrices;
    private javax.swing.JButton btnPerformanceReports;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
