/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.workSpaceProfiles;

import model.Business.Business;
import model.CustomerManagement.CustomerProfile;
import model.SalesManagement.SalesPersonProfile;
import ui.workSpaceProfiles.OrderManagement.ProcessOrder;

/**
 *
 * @author KAILASH
 */
public class SalesPersonWorkAreaJPanel extends javax.swing.JPanel {

    javax.swing.JPanel CardSequencePanel;
    Business business;
    SalesPersonProfile salesperson;
    /**
     * Creates new form SalesPersonWorkAreaJapanel
     */
    public SalesPersonWorkAreaJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCustName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnProcessOrder = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Customer Details (ID)");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        txtCustName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustNameActionPerformed(evt);
            }
        });
        add(txtCustName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 150, -1));

        jButton1.setText("jButton1");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 130, -1));

        btnProcessOrder.setText("Process Order");
        btnProcessOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessOrderActionPerformed(evt);
            }
        });
        add(btnProcessOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 130, -1));

        jButton3.setText("jButton1");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 130, -1));

        jButton4.setText("jButton1");
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 130, -1));

        jButton5.setText("jButton1");
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 130, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtCustNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustNameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtCustNameActionPerformed

    private void btnProcessOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessOrderActionPerformed
        // TODO add your handling code here:
        String customername = txtCustName.getText();
        if (customername.isEmpty()) return;
        CustomerProfile selectedcustomer = business.getCustomerDirectory().findCustomer(customername);

        ProcessOrder aos = new ProcessOrder(business, selectedcustomer ,salesperson, CardSequencePanel);

        CardSequencePanel.add("ManageVulns", aos);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnProcessOrderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcessOrder;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtCustName;
    // End of variables declaration//GEN-END:variables
}
