/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.workSpaceProfiles;

import model.Business.Business;
import model.CustomerManagement.CustomerProfile;
import model.SalesManagement.SalesPersonProfile;
import ui.workSpaceProfiles.OrderManagement.ProcessOrder;

/**
 *
 * @author KAILASH
 */
public class SalesPersonWorkAreaJPanel extends javax.swing.JPanel {

    javax.swing.JPanel CardSequencePanel;
    Business business;
    SalesPersonProfile salesperson;
    /**
     * Creates new form SalesPersonWorkAreaJapanel
     */
    public SalesPersonWorkAreaJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCustName = new javax.swing.JTextField();
        btnServeCustomers = new javax.swing.JButton();
        btnManageProfile = new javax.swing.JButton();
        btnReviewOrderStatusHistory = new javax.swing.JButton();
        btnReviewComission = new javax.swing.JButton();
        btnPerformanceReports = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Customer Details (ID)");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        txtCustName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustNameActionPerformed(evt);
            }
        });
        add(txtCustName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 150, -1));

        btnServeCustomers.setBackground(new java.awt.Color(102, 153, 255));
        btnServeCustomers.setForeground(new java.awt.Color(255, 255, 255));
        btnServeCustomers.setText("Serve Customers");
        btnServeCustomers.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnServeCustomers.setMaximumSize(new java.awt.Dimension(200, 40));
        btnServeCustomers.setMinimumSize(new java.awt.Dimension(20, 23));
        btnServeCustomers.setPreferredSize(new java.awt.Dimension(240, 30));
        btnServeCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServeCustomersIdentifyResourceAssetsActionPerformed(evt);
            }
        });
        add(btnServeCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        btnManageProfile.setBackground(new java.awt.Color(102, 153, 255));
        btnManageProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnManageProfile.setText("Manage Profile");
        btnManageProfile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageProfile.setMaximumSize(new java.awt.Dimension(200, 40));
        btnManageProfile.setMinimumSize(new java.awt.Dimension(20, 20));
        btnManageProfile.setPreferredSize(new java.awt.Dimension(240, 25));
        btnManageProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageProfileActionPerformed(evt);
            }
        });
        add(btnManageProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        btnReviewOrderStatusHistory.setBackground(new java.awt.Color(102, 153, 255));
        btnReviewOrderStatusHistory.setForeground(new java.awt.Color(255, 255, 255));
        btnReviewOrderStatusHistory.setText("Review Order Status History");
        btnReviewOrderStatusHistory.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReviewOrderStatusHistory.setMaximumSize(new java.awt.Dimension(200, 40));
        btnReviewOrderStatusHistory.setMinimumSize(new java.awt.Dimension(20, 20));
        btnReviewOrderStatusHistory.setPreferredSize(new java.awt.Dimension(240, 25));
        btnReviewOrderStatusHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReviewOrderStatusHistoryActionPerformed(evt);
            }
        });
        add(btnReviewOrderStatusHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, -1, -1));

        btnReviewComission.setBackground(new java.awt.Color(102, 153, 255));
        btnReviewComission.setForeground(new java.awt.Color(255, 255, 255));
        btnReviewComission.setText("Review Comission");
        btnReviewComission.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReviewComission.setMaximumSize(new java.awt.Dimension(200, 40));
        btnReviewComission.setMinimumSize(new java.awt.Dimension(20, 20));
        btnReviewComission.setPreferredSize(new java.awt.Dimension(240, 25));
        btnReviewComission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReviewComissionActionPerformed(evt);
            }
        });
        add(btnReviewComission, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, -1));

        btnPerformanceReports.setBackground(new java.awt.Color(102, 153, 255));
        btnPerformanceReports.setForeground(new java.awt.Color(255, 255, 255));
        btnPerformanceReports.setText("Performance Reports");
        btnPerformanceReports.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPerformanceReports.setMaximumSize(new java.awt.Dimension(200, 40));
        btnPerformanceReports.setMinimumSize(new java.awt.Dimension(20, 20));
        btnPerformanceReports.setPreferredSize(new java.awt.Dimension(240, 25));
        btnPerformanceReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerformanceReportsActionPerformed(evt);
            }
        });
        add(btnPerformanceReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtCustNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustNameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtCustNameActionPerformed

    private void btnServeCustomersIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServeCustomersIdentifyResourceAssetsActionPerformed

        // TODO add your handling code here:

        String customername = txtCustName.getText();
        if (customername.isEmpty()) return;
        CustomerProfile selectedcustomer = business.getCustomerDirectory().findCustomer(customername);

        ProcessOrder aos = new ProcessOrder(business, selectedcustomer ,salesperson, CardSequencePanel);

        CardSequencePanel.add("ManageVulns", aos);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnServeCustomersIdentifyResourceAssetsActionPerformed

    private void btnManageProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageProfileActionPerformed
        // TODO add your handling code here:

        //        ManageVulns aos = new  ManageVulns(businessunit, CardSequencePanel);
        // aos.setAgenda(businessunit.getRiskManagementAgenda());
        //        CardSequencePanel.add("ManageVulns", aos);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnManageProfileActionPerformed

    private void btnReviewOrderStatusHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReviewOrderStatusHistoryActionPerformed
        // TODO add your handling code here:

        ManageSalesPersonOrders iet = new ManageSalesPersonOrders(business, CardSequencePanel);

        CardSequencePanel.add("FindResourceAsset", iet);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnReviewOrderStatusHistoryActionPerformed

    private void btnReviewComissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReviewComissionActionPerformed
        // TODO add your handling code here:

        CardSequencePanel.removeAll();
        //      ViewBusinessUnitRiskProfile drpd= new ViewBusinessUnitRiskProfile(businessunit, CardSequencePanel);
        //        ManageHazards drpd = new ManageHazards(businessunit, CardSequencePanel);
        //        CardSequencePanel.add("ManageRiskProfiles", drpd);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnReviewComissionActionPerformed

    private void btnPerformanceReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerformanceReportsActionPerformed
        // TODO add your handling code here:

        CardSequencePanel.removeAll();
        //        ManageIncidents aos = new  ManageIncidents(businessunit, CardSequencePanel);
        // aos.setAgenda(businessunit.getRiskManagementAgenda());
        //        CardSequencePanel.add("RiskAgendaObjectives", aos);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnPerformanceReportsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageProfile;
    private javax.swing.JButton btnPerformanceReports;
    private javax.swing.JButton btnReviewComission;
    private javax.swing.JButton btnReviewOrderStatusHistory;
    private javax.swing.JButton btnServeCustomers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtCustName;
    // End of variables declaration//GEN-END:variables
}
